# Generated by Django 3.2.5 on 2021-07-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('network_size', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=400)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ip_addresses.networkaddress')),
            ],
        ),
    ]
